export const GET_POKEMON_NAME = 'GET_POKEMON_NAME';
export const GET_POKEMON_NAME_PENDING = 'GET_POKEMON_NAME_PENDING';
export const GET_POKEMON_NAME_FULFILLED = 'GET_POKEMON_NAME_FULFILLED';
export const GET_POKEMON_NAME_REJECTED = 'GET_POKEMON_NAME_REJECTED';